aria:
  client:
    songRootUrl: "http://localhost:8089/"
    scoreRootUrl: "http://localhost:8087/"
    clientId: adminId
    clientSecret: adminSecret
    tokenUrl: http://localhost:8081/oauth/token
    retryMaxAttempts: 3
    retryDelaySec: 10
